
Python Version Check

In [1]:
import sys
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, World!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


explaination:This code checks if Python is version 3.6 or higher and prints the version safely, using proper indentation to avoid errors

3.2 Data Types in Python

In [2]:
my_list = [1, 2, 3]
print("Original List:", my_list)
my_list.append(4)
print("Modified List:", my_list)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)



Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)

Difference between Mutable and Immutable Data Types.


3.2.1 Some Common Data Types in Python:

In [3]:
age = 23
pi = 3.14
temperature = -5.5
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))


data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>



Data Types - Numeric like int, float, complex


Sequence:

In [4]:
name = "Alice"
greeting = 'Hello'
address = "123 Main St"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


Data Types - Sequence - String

In [5]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

Data Types - Sequence - List

In [6]:
colors = ['red', 'green', 'yellow', 'blue']
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])
colors[0] = 'purple'
print("Updated colors:", colors)

First element: red
Last two elements: ['yellow', 'blue']
Middle two elements: ['green', 'yellow']
Updated colors: ['purple', 'green', 'yellow', 'blue']



Mapping:

In [7]:
person = {'name': 'John', 'age': 30, 'city': 'Pittsburgh'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']



Set:

In [8]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}



Boolean:

Data Types - Set

In [9]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


Data Types - Boolean

3.4 Logical Statements:

In [10]:
num = 10

if num > 0:
    print("Positive")
elif num == 0:
    print("Zero")
else:
    print("Non-positive")

Positive


In [11]:
x = 5
y = 10
if x > 0 and y < 20:
    print("Both conditions are true")
if x > 0 or y > 20:
    print("At least one condition is true")
if not x == 0:
    print("x is not equal to 0")


Both conditions are true
At least one condition is true
x is not equal to 0


In [12]:
a = True
b = False
if a and b:
    print("Both a and b are True")
else:
    print("Either a or b is False")
if a or b:
    print("At least one of a or b is True")
else:
    print("Both a and b are False")
if not a:
    print("a is False")
else:
    print("a is True")

Either a or b is False
At least one of a or b is True
a is True



3.4.1 Loops:

In [13]:
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)
count = 0
while count < 5:
    print("Count is:", count)
    count += 1
fruits = ["apple", "banana", "orange"]
print("loop 1")
for fruit in fruits:
    print(fruit)
    if fruit == "apple":
        break
print("loop 2")
for fruit in fruits:
    if fruit == "apple":
        continue
    else:
        print(fruit)

apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
loop 2
banana
orange


Every block inside for, while, if, else must be indented (usually 4 spaces).

Without proper indentation, Python will throw IndentationError

In [ ]:
3.5 Functions.

3.6 Anatomy of a Function:

In [15]:
def add_binary(a, b):
    """
    Returns the sum of two decimal numbers in binary digits.

    Parameters:
    a (int): A decimal integer
    b (int): Another decimal integer

    Returns:
    binary_sum (str): Binary string of the sum of a and b
    """
    binary_sum = bin(a + b)[2:]
    return binary_sum


3.6.1 Built - in - Functions:

In [16]:
print("Hello, World!")
length = len("Hello")
data_type = type(42)
total = sum([1, 2, 3])


Hello, World!


3.6.2 Built - in - Methods

In [17]:

print("Hello, World!")
length = len("Hello")
data_type = type(42)
total = sum([1, 2, 3])

Hello, World!



3.6.2 Built - in - Methods

In [18]:

message = "hello".upper()
fruits = ["apple", "banana"]
fruits.append("cherry")
info = {"name": "Alice", "age": 25}
age = info.get("age")


3.6.3 User - Defined - Function:

In [19]:
def temperature_converter():
    """
    Converts temperature between Celsius and Fahrenheit.

    This function prompts the user to specify the conversion type (Celsius to Fahrenheit
    or Fahrenheit to Celsius) and then asks for the temperature value.
    It calculates and returns the converted temperature.

    Returns:
    float: The converted temperature value.
    """

    print("Choose conversion type:")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")
    choice = input("Enter 1 or 2: ")

    if choice == "1":
        celsius = float(input("Enter temperature in Celsius: "))
        fahrenheit = (celsius * 9/5) + 32
        print(f"{celsius}C is equal to {fahrenheit}F")
        return fahrenheit

    elif choice == "2":
        fahrenheit = float(input("Enter temperature in Fahrenheit: "))
        celsius = (fahrenheit - 32) * 5/9
        print(f"{fahrenheit}F is equal to {celsius}C")
        return celsius

    else:
        print("Invalid choice. Please enter 1 or 2.")
        return None
temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 2
Enter temperature in Fahrenheit: 54
54.0F is equal to 12.222222222222221C


12.222222222222221

Example of well-structured user-defined function

3.7 Global and Local Variables:

In [20]:

x = 10

def print_global():
    print(x)
print_global()

10



Local Variables:

In [21]:

def print_local():
    y = 5
    print(y)

print_local()


5


4 TO - DO - Task

4.1 Exercise on Functions: Task - 1:

In [23]:
def convert_units(conversion_type, value, direction):
    """
    Converts units based on the conversion type and direction.

    Parameters:
    conversion_type (str): Type of conversion (1=Length, 2=Weight, 3=Volume)
    value (float): Value to convert
    direction (int): Conversion direction

    Returns:
    float: Converted value or None if invalid
    """
    if conversion_type == "1":
        if direction == 1:
            return value * 3.28084
        elif direction == 2:
            return value * 0.3048
    elif conversion_type == "2":
        if direction == 1:
            return value * 2.20462
        elif direction == 2:
            return value * 0.453592
    elif conversion_type == "3":
        if direction == 1:
            return value * 0.264172
        elif direction == 2:
            return value * 3.78541
    return None # Added a return None here for cases where no valid conversion direction is matched

while True:

    print("\n===== Unit Conversion Program =====")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")
    print("4. Exit")

    conversion_type = input("Choose conversion type (1/2/3/4): ")
    if conversion_type == "4":
        print("Thank you for using the program!")
        break
    if conversion_type not in ["1", "2", "3"]:
        print("Error: Invalid conversion type.")
        continue
    try:
        value = float(input("Enter value to convert: "))
    except ValueError:
        print("Error: Please enter a valid number.")
        continue
    if conversion_type == "1":
        print("1. Meters to Feet")
        print("2. Feet to Meters")

    elif conversion_type == "2":
        print("1. Kilograms to Pounds")
        print("2. Pounds to Kilograms")

    elif conversion_type == "3":
        print("1. Liters to Gallons")
        print("2. Gallons to Liters")
    try:
        direction = int(input("Choose conversion direction (1/2): "))
    except ValueError:
        print("Error: Invalid option.")
        continue
    # Corrected indentation for the 'result' assignment
    result = convert_units(conversion_type, value, direction)

    if result is not None:
        print("Converted value =", round(result, 4))
    else:
        print("Error: Invalid conversion direction.")


===== Unit Conversion Program =====
1. Length
2. Weight
3. Volume
4. Exit
Choose conversion type (1/2/3/4): 2
Enter value to convert: 10
1. Kilograms to Pounds
2. Pounds to Kilograms
Choose conversion direction (1/2): 1
Converted value = 22.0462

===== Unit Conversion Program =====
1. Length
2. Weight
3. Volume
4. Exit
Choose conversion type (1/2/3/4): 4
Thank you for using the program!


Task - 2:

In [26]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The total sum of the numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average value of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Finds the maximum number in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The largest number in the list.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum number in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The smallest number in the list.
    """
    return min(numbers)
while True:
    print("\n===== Math Operations Program =====")
    print("1. Find Sum")
    print("2. Find Average")
    print("3. Find Maximum")
    print("4. Find Minimum")
    print("5. Exit")

    choice = input("Choose an operation (1-5): ")

    if choice == "5":
        print("Thank you for using the program!")
        break

    if choice not in ["1", "2", "3", "4"]:
        print("Error: Invalid choice.")
        continue
    user_input = input("Enter numbers separated by spaces: ")

    try:
        numbers = list(map(float, user_input.split()))

        if len(numbers) == 0:
            raise ValueError("Empty list")

    except ValueError:
        print("Error: Please enter valid numeric values.")
        continue
    if choice == "1":
        result = calculate_sum(numbers)
        print("Sum =", result)

    elif choice == "2":
        result = calculate_average(numbers)
        print("Average =", result)

    elif choice == "3":
        result = find_maximum(numbers)
        print("Maximum =", result)

    elif choice == "4":
        result = find_minimum(numbers)
        print("Minimum =", result)



===== Math Operations Program =====
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
5. Exit
Choose an operation (1-5): 2
Enter numbers separated by spaces: 2
Average = 2.0

===== Math Operations Program =====
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
5. Exit
Choose an operation (1-5): 4
Enter numbers separated by spaces: 123
Minimum = 123.0

===== Math Operations Program =====
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
5. Exit
Choose an operation (1-5): 1
Enter numbers separated by spaces: 1 2
Sum = 3.0

===== Math Operations Program =====
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
5. Exit
Choose an operation (1-5): 5
Thank you for using the program!


4.2 Exercise on List Manipulation:


In [27]:
def extract_every_other(lst):
    """
    Extracts every other element from the list starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element.
    """
    return lst[::2]
try:
    user_input = input("Enter elements separated by spaces: ")
    lst = user_input.split()

    if len(lst) == 0:
        raise ValueError

    result = extract_every_other(lst)

    print("Original List:", lst)
    print("Extracted List:", result)

except ValueError:
    print("Error: Please enter valid elements.")

Enter elements separated by spaces: 1 2 3 4 5 6
Original List: ['1', '2', '3', '4', '5', '6']
Extracted List: ['1', '3', '5']



2. Slice a Sublist:

In [28]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list between start and end indices (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): Starting index.
    end (int): Ending index.

    Returns:
    list: Sublist from start to end (inclusive).
    """
    return lst[start:end+1]
try:
    user_input = input("Enter elements separated by spaces: ")
    lst = user_input.split()

    if len(lst) == 0:
        raise ValueError

    start = int(input("Enter start index: "))
    end = int(input("Enter end index: "))

    if start < 0 or end >= len(lst) or start > end:
        raise IndexError

    result = get_sublist(lst, start, end)

    print("Original List:", lst)
    print("Sublist:", result)

except ValueError:
    print("Error: Please enter valid elements and indices.")

except IndexError:
    print("Error: Invalid index range.")


Enter elements separated by spaces: 1 2 3 4 5 6
Enter start index: 2
Enter end index: 4
Original List: ['1', '2', '3', '4', '5', '6']
Sublist: ['3', '4', '5']


3. Reverse a List Using Slicing:

In [29]:
def reverse_list(lst):
    """
    Reverses the given list using slicing.

    Parameters:
    lst (list): The original list.

    Returns:
    list: Reversed list.
    """
    return lst[::-1]
try:
    user_input = input("Enter elements separated by spaces: ")
    lst = user_input.split()

    if len(lst) == 0:
        raise ValueError

    result = reverse_list(lst)

    print("Original List:", lst)
    print("Reversed List:", result)

except ValueError:
    print("Error: Please enter valid elements.")

Enter elements separated by spaces: 1 2 3 4 5
Original List: ['1', '2', '3', '4', '5']
Reversed List: ['5', '4', '3', '2', '1']


4. Remove the First and Last Elements:

In [30]:

def remove_first_last(lst):
    """
    Removes the first and last elements from the list.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]
try:
    user_input = input("Enter elements separated by spaces: ")
    lst = user_input.split()

    if len(lst) < 2:
        raise ValueError

    result = remove_first_last(lst)

    print("Original List:", lst)
    print("Updated List:", result)

except ValueError:
    print("Error: List must contain at least two elements.")

Enter elements separated by spaces: 1 2 3 4 5
Original List: ['1', '2', '3', '4', '5']
Updated List: ['2', '3', '4']



5. Get the First n Elements:

In [31]:
def get_first_n(lst, n):
    """
    Returns the first n elements of a list using slicing.

    Parameters:
    lst (list): The original list.
    n (int): Number of elements to extract.

    Returns:
    list: A new list containing the first n elements.
    """
    return lst[:n]
try:
    user_input = input("Enter elements separated by spaces: ")
    lst = user_input.split()

    if len(lst) == 0:
        raise ValueError

    n = int(input("Enter number of elements to extract: "))

    if n < 0 or n > len(lst):
        raise IndexError

    result = get_first_n(lst, n)

    print("Original List:", lst)
    print(f"First {n} elements:", result)

except ValueError:
    print("Error: Please enter valid elements and a number.")

except IndexError:
    print("Error: n must be between 0 and the length of the list.")

Enter elements separated by spaces: 1 2 3 4 5
Enter number of elements to extract: 3
Original List: ['1', '2', '3', '4', '5']
First 3 elements: ['1', '2', '3']


6. Extract Elements from the End:


In [32]:
def get_last_n(lst, n):
    """
    Returns the last n elements of a list using slicing.

    Parameters:
    lst (list): The original list.
    n (int): Number of elements to extract from the end.

    Returns:
    list: A new list containing the last n elements.
    """
    return lst[-n:]
try:
    user_input = input("Enter elements separated by spaces: ")
    lst = user_input.split()

    if len(lst) == 0:
        raise ValueError

    n = int(input("Enter number of elements to extract from the end: "))

    if n < 0 or n > len(lst):
        raise IndexError

    result = get_last_n(lst, n)

    print("Original List:", lst)
    print(f"Last {n} elements:", result)

except ValueError:
    print("Error: Please enter valid elements and a number.")

except IndexError:
    print("Error: n must be between 0 and the length of the list.")

Enter elements separated by spaces: 1 2 3 4 5
Enter number of elements to extract from the end: 2
Original List: ['1', '2', '3', '4', '5']
Last 2 elements: ['4', '5']


7. Extract Elements in Reverse Order:

In [33]:
def reverse_skip(lst):
    """
    Extracts every second element in reverse order starting from the second-to-last element.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list containing every second element in reverse order from second-to-last.
    """
    return lst[-2::-2]
try:
    user_input = input("Enter elements separated by spaces: ")
    lst = user_input.split()

    if len(lst) < 2:
        raise ValueError

    result = reverse_skip(lst)

    print("Original List:", lst)
    print("Reversed Skip List:", result)

except ValueError:
    print("Error: List must contain at least two elements.")

Enter elements separated by spaces: 1 2 3 4 5 6
Original List: ['1', '2', '3', '4', '5', '6']
Reversed Skip List: ['5', '3', '1']


4.3 Exercise on Nested List:

1. Flatten a Nested List:

In [34]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst (list of lists): The nested list to flatten.

    Returns:
    list: A flattened single-dimensional list.
    """
    flat_list = []
    for sublist in lst:
        for item in sublist:
            flat_list.append(item)
    return flat_list

try:
    user_input = input("Enter nested list elements (e.g., [[1,2],[3,4],[5]]): ")
    nested_list = eval(user_input)

    if not all(isinstance(sublist, list) for sublist in nested_list):
        raise ValueError

    result = flatten(nested_list)

    print("Nested List:", nested_list)
    print("Flattened List:", result)

except (SyntaxError, ValueError):
    print("Error: Please enter a valid nested list.")

Enter nested list elements (e.g., [[1,2],[3,4],[5]]): [[1,2],[3,4],[5]]
Nested List: [[1, 2], [3, 4], [5]]
Flattened List: [1, 2, 3, 4, 5]



2. Accessing Nested List Elements:

In [35]:
def access_nested_element(lst, indices):
    """
    Accesses a specific element from a nested list using a list of indices.

    Parameters:
    lst (list): The nested list.
    indices (list): A list of indices to traverse the nested list.

    Returns:
    element: The element at the specified nested position.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element
try:
    user_input = input("Enter nested list (e.g., [[1,2,3],[4,5,6],[7,8,9]]): ")
    nested_list = eval(user_input)

    indices_input = input("Enter indices separated by spaces (e.g., 1 2): ")
    indices = list(map(int, indices_input.split()))

    result = access_nested_element(nested_list, indices)

    print("Nested List:", nested_list)
    print("Accessed Element:", result)

except (IndexError, TypeError):
    print("Error: Invalid indices for the given nested list.")

except (SyntaxError, ValueError):
    print("Error: Please enter a valid nested list and indices.")

Enter nested list (e.g., [[1,2,3],[4,5,6],[7,8,9]]): [[1,2,3],[4,5,6],[7,8,9]]
Enter indices separated by spaces (e.g., 1 2): 1 2
Nested List: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Accessed Element: 6


3. Sum of All Elements in a Nested List:

In [36]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list of any depth.

    Parameters:
    lst (list): The nested list containing numbers and/or sublists.

    Returns:
    int/float: The sum of all numbers in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total
try:
    user_input = input("Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): ")
    import ast
    nested_list = ast.literal_eval(user_input)

    result = sum_nested(nested_list)

    print("Nested List:", nested_list)
    print("Sum of all elements:", result)

except (SyntaxError, ValueError):
    print("Error: Please enter a valid nested list containing numbers only.")

Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): [[1,2],[3,[4,5]],6]
Nested List: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


4. Remove Specific Element from a Nested List;

In [37]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list of lists): The nested list.
    elem: The element to remove.

    Returns:
    list: Modified nested list with all occurrences of elem removed.
    """
    result = []
    for sublist in lst:
        if isinstance(sublist, list):
            new_sublist = [x for x in sublist if x != elem]
            result.append(new_sublist)
        else:
            if sublist != elem:
                result.append(sublist)
    return result
try:
    user_input = input("Enter a nested list (e.g., [[1,2],[3,2],[4,5]]): ")

    import ast
    nested_list = ast.literal_eval(user_input)

    elem_input = input("Enter the element to remove: ")
    try:
        elem = int(elem_input)
    except ValueError:
        try:
            elem = float(elem_input)
        except ValueError:
            elem = elem_input

    result = remove_element(nested_list, elem)

    print("Original List:", nested_list)
    print("Modified List:", result)

except (SyntaxError, ValueError):
  print("Error: Please enter a valid nested list.")

Enter a nested list (e.g., [[1,2],[3,2],[4,5]]): [[1,2],[3,2],[4,5]]
Enter the element to remove: 2
Original List: [[1, 2], [3, 2], [4, 5]]
Modified List: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

In [38]:
def find_max(lst):
    """
    Finds the maximum element in a nested list of any depth.

    Parameters:
    lst (list): The nested list containing numbers and/or sublists.

    Returns:
    int/float: The maximum element in the nested list.
    """
    current_max = float('-inf')
    for item in lst:
        if isinstance(item, list):
            sub_max = find_max(item)
            if sub_max > current_max:
                current_max = sub_max
        else:
            if item > current_max:
                current_max = item
    return current_max
try:
    user_input = input("Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): ")

    import ast
    nested_list = ast.literal_eval(user_input)

    result = find_max(nested_list)

    print("Nested List:", nested_list)
    print("Maximum Element:", result)

except (SyntaxError, ValueError):
    print("Error: Please enter a valid nested list containing numbers only.")

Enter a nested list (e.g., [[1,2],[3,[4,5]],6]):  [[1, 2], [3, [4, 5]], 6]
Nested List: [[1, 2], [3, [4, 5]], 6]
Maximum Element: 6


6. Count Occurrences of an Element in a Nested List:

In [39]:
def count_occurrences(lst, elem):
    """
    Counts the occurrences of a specific element in a nested list.

    Parameters:
    lst (list): The nested list containing elements and/or sublists.
    elem: The element to count.

    Returns:
    int: Number of times elem occurs in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
            if item == elem:
                count += 1
    return count
try:
    user_input = input("Enter a nested list (e.g., [[1,2],[2,3],[2,4]]): ")

    import ast
    nested_list = ast.literal_eval(user_input)

    elem_input = input("Enter the element to count: ")
    try:
        elem = int(elem_input)
    except ValueError:
        try:
            elem = float(elem_input)
        except ValueError:
            elem = elem_input

    result = count_occurrences(nested_list, elem)
    print("Nested List:", nested_list)
    print(f"Occurrences of {elem}:", result)

except (SyntaxError, ValueError):
    print("Error: Please enter a valid nested list.")


Enter a nested list (e.g., [[1,2],[2,3],[2,4]]): [[1, 2], [2, 3], [2, 4]]
Enter the element to count: 2
Nested List: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 0


7. Flatten a List of Lists of Lists:

In [40]:
def deep_flatten(lst):
    """
    Recursively flattens a deeply nested list into a single list.

    Parameters:
    lst (list): The nested list of any depth.

    Returns:
    list: A single flattened list containing all elements.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list
try:
    user_input = input("Enter a deeply nested list (e.g., [[[1,2],[3,4]],[[5,6],[7,8]]]): ")

    import ast
    nested_list = ast.literal_eval(user_input)

    result = deep_flatten(nested_list)

    print("Nested List:", nested_list)
    print("Flattened List:", result)

except (SyntaxError, ValueError):
    print("Error: Please enter a valid nested list.")

Enter a deeply nested list (e.g., [[[1,2],[3,4]],[[5,6],[7,8]]]): [[[1,2],[3,4]],[[5,6],[7,8]]]
Nested List: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened List: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

In [41]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
    lst (list): The nested list containing numbers and/or sublists.

    Returns:
    float: The average of all elements in the nested list.
    """
    def flatten(l):
        """Helper function to flatten nested list of any depth."""
        flat = []
        for item in l:
            if isinstance(item, list):
                flat.extend(flatten(item))
            else:
                flat.append(item)
        return flat

    flat_list = flatten(lst)
    if len(flat_list) == 0:
        return 0
    return sum(flat_list) / len(flat_list)
try:
    user_input = input("Enter a nested list (e.g., [[1,2],[3,4],[5,6]]): ")

    import ast
    nested_list = ast.literal_eval(user_input)

    result = average_nested(nested_list)

    print("Nested List:", nested_list)
    print("Average of all elements:", result)

except (SyntaxError, ValueError):
    print("Error: Please enter a valid nested list containing numbers.")


Enter a nested list (e.g., [[1,2],[3,4],[5,6]]): [[[1,2],[3,4]],[[5,6],[7,8]]]
Nested List: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Average of all elements: 4.5


10 To - Do - NumPy


10.1 Basic Vector and Matrix Operation with NumPy

In [43]:
import numpy as np
empty_array = np.empty((2,2))
print("Empty Array 2x2:\n", empty_array)
ones_array = np.ones((4,2))
print("\nAll Ones Array 4x2:\n", ones_array)
filled_array = np.full((3,3), 7)
print("\nFilled Array 3x3 with 7:\n", filled_array)
zeros_like_array = np.zeros_like(filled_array)
print("\nZeros Like Filled Array:\n", zeros_like_array)
ones_like_array = np.ones_like(filled_array)
print("\nOnes Like Filled Array:\n", ones_like_array)
new_list = [1,2,3,4]
array_from_list = np.array(new_list)
print("\nArray from list:", array_from_list)

Empty Array 2x2:
 [[4.85837412e-315 0.00000000e+000]
 [5.78926361e-317 5.78940590e-317]]

All Ones Array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array 3x3 with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Filled Array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones Like Filled Array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Array from list: [1 2 3 4]


Problem 2: Array Manipulation, Ranges, Indexing

In [44]:
arr_10_49 = np.arange(10, 50)
print("\nArray 10 to 49:\n", arr_10_49)


matrix_3x3 = np.arange(9).reshape(3,3)
print("\n3x3 Matrix:\n", matrix_3x3)


identity_3x3 = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_3x3)


rand_array_30 = np.random.random(30)
print("\nRandom Array 30:\n", rand_array_30)
print("Mean:", rand_array_30.mean())


rand_10x10 = np.random.random((10,10))
print("\n10x10 Random Array:\n", rand_10x10)
print("Min:", rand_10x10.min(), "Max:", rand_10x10.max())

zero_array_10 = np.zeros(10)
zero_array_10[4] = 1
print("\nZero Array with 5th element 1:", zero_array_10)
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print("\nReversed Array:", reversed_arr)
array_border = np.ones((5,5))
array_border[1:-1,1:-1] = 0
print("\n2D Array with 1 border:\n", array_border)
checkerboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array 30:
 [0.66856281 0.37998859 0.27407722 0.66282382 0.09433409 0.42865028
 0.16645599 0.40776517 0.28532135 0.37043976 0.60045648 0.88525442
 0.01570139 0.76507819 0.01675556 0.05062622 0.28822284 0.40016248
 0.26950908 0.48595029 0.46856616 0.36659836 0.91654944 0.80887025
 0.90390877 0.55140842 0.13581104 0.68286126 0.09795028 0.142975  ]
Mean: 0.41972116693022604

10x10 Random Array:
 [[0.84765455 0.43552664 0.63048276 0.28006249 0.07637988 0.60840788
  0.10530618 0.48360108 0.08316864 0.76737419]
 [0.08779635 0.10706144 0.0655875  0.8654935  0.95718764 0.77234355
  0.09338638 0.06396452 0.64458764 0.34322195]
 [0.67994947 0.21391408 0.01937566 0.40271268 0.83417949 0.72708924
  0.39793014 0.12845966 0.40213718 0.80485403]
 [0.74389

Problem 3: Array Operations

In [45]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("\nAdd x + y:\n", x + y)
print("\nSubtract x - y:\n", x - y)
print("\nMultiply x by 3:\n", x * 3)
print("\nSquare of x:\n", x**2)
print("\nDot product v.w:", np.dot(v, w))
print("Dot product x.v:", np.dot(x, v))
print("Dot product x.y:\n", np.dot(x, y))
concat_row = np.concatenate((x,y), axis=0)
concat_col = np.concatenate((v,w), axis=0)
print("\nConcatenate x and y along rows:\n", concat_row)
print("Concatenate v and w (column-wise equivalent):", concat_col)
try:
    np.concatenate((x,v), axis=0)
except ValueError as e:
    print("\nConcatenating x and v Error:", e)
    print("Reason: Shapes are not compatible for concatenation")


Add x + y:
 [[ 6  8]
 [10 13]]

Subtract x - y:
 [[-4 -4]
 [-4 -3]]

Multiply x by 3:
 [[ 3  6]
 [ 9 15]]

Square of x:
 [[ 1  4]
 [ 9 25]]

Dot product v.w: 219
Dot product x.v: [29 77]
Dot product x.y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w (column-wise equivalent): [ 9 10 11 12]

Concatenating x and v Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: Shapes are not compatible for concatenation


Problem 4: Matrix Operations


In [46]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("\nA * A^-1:\n", identity_check)
AB = np.dot(A,B)
BA = np.dot(B,A)
print("\nAB:\n", AB)
print("BA:\n", BA)
print("AB == BA ?", np.array_equal(AB, BA))


AB_T = (np.dot(A,B)).T
B_TA_T = np.dot(B.T, A.T)
print("\n(AB)^T:\n", AB_T)
print("B^T A^T:\n", B_TA_T)
print("Equal?", np.array_equal(AB_T, B_TA_T))

# Solve system of linear equations
# 2x -3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

A_matrix = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B_matrix = np.array([-1,-3,9])

X = np.linalg.solve(A_matrix, B_matrix)
print("\nSolution of the system [x, y, z]:", X)
X_inv = np.dot(np.linalg.inv(A_matrix), B_matrix)
print("Solution using inverse method:", X_inv)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA ? False

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Equal? True

Solution of the system [x, y, z]: [ 2.  1. -2.]
Solution using inverse method: [ 2.  1. -2.]


10.2 Experiment: How Fast is NumPy?


1. Element-wise Addition

Add blockquote

In [47]:
import numpy as np
import time

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
list_add = [a + b for a, b in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start, "seconds")


arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
np_add = arr1 + arr2
end = time.time()
print("NumPy addition time:", end - start, "seconds")

Python list addition time: 0.0712730884552002 seconds
NumPy addition time: 0.00459599494934082 seconds


2. Element-wise Multiplication

In [48]:
import numpy as np
import time

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
list_mul = [a * b for a, b in zip(list1, list2)]
end = time.time()
print("Python list multiplication time:", end - start, "seconds")
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
np_mul = arr1 * arr2
end = time.time()
print("NumPy multiplication time:", end - start, "seconds")

Python list multiplication time: 0.07919144630432129 seconds
NumPy multiplication time: 0.005851030349731445 seconds


3. Dot Product

In [49]:
import numpy as np
import time

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
dot_list = sum(a * b for a, b in zip(list1, list2))
end = time.time()
print("Python list dot product time:", end - start, "seconds")
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print("NumPy dot product time:", end - start, "seconds")

Python list dot product time: 0.17488479614257812 seconds
NumPy dot product time: 0.0017595291137695312 seconds


4. Matrix Multiplication

In [51]:
import numpy as np
import time

matrix_size = 1000
matrix1 = [[i+j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2 = [[i+j for j in range(matrix_size)] for i in range(matrix_size)]

start = time.time()
result_matrix = [[0]*matrix_size for _ in range(matrix_size)]
for i in range(matrix_size):
    for j in range(matrix_size):
        for k in range(matrix_size):
            result_matrix[i][j] += matrix1[i][k] * matrix2[k][j]
end = time.time()
print("Python list matrix multiplication time:", end - start, "seconds")


np_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
np_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

start = time.time()
np_result = np.dot(np_matrix1, np_matrix2)
end = time.time()
print("NumPy matrix multiplication time:", end - start, "seconds")

Python list matrix multiplication time: 389.08240699768066 seconds
NumPy matrix multiplication time: 1.6859357357025146 seconds
